apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: tk-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tk-app
  minReplicas: 1                # Mínimo de pods
  maxReplicas: 10               # Máximo de pods (ajuste conforme limite do cluster)
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60    # Escala quando média de uso da CPU passar de 50%
